sudo: false
language: go
go:
- 1.9
- tip

before_install:
- go get golang.org/x/tools/cmd/cover
- go get -u github.com/golang/dep/...

install:
- dep ensure
- dep status

script:
- go test -i ./...
- go test -cover ./...
- go test -race ./...
- go build
- ./changelog
