sudo: required
language: go
go:
- 1.9
- tip

services:
  - docker

env:
- CGO_ENABLED=1

before_install:
- go get golang.org/x/tools/cmd/cover
- go get -u github.com/golang/dep/...

install:
- dep ensure
- dep status

script:
- go test -i ./...
- go test -cover ./...
- go test -race ./...
- go build
- ./changelog
- docker build -t skuid/changelog .

after_success:
   - if [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_GO_VERSION" == "1.9" ]; then
     docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io;
     docker tag skuid/changelog quay.io/skuid/changelog:$TRAVIS_TAG;
     docker push quay.io/skuid/changelog:$TRAVIS_TAG;
     fi
   - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_GO_VERSION" == "1.9" ]; then
     docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io;
     docker tag skuid/changelog quay.io/skuid/changelog:master;
     docker push quay.io/skuid/changelog:master;
     fi
